[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  revision = "66487607e2081c7c2af2281c62c14ee000d5024b"
  name = "golang.org/x/tools"

[prune]
  go-tests = true
  unused-packages = true
